export const SAVE_DEAL_FORM = 'SAVE_DEALFORM';
export const SAVE_INVOICE_FORM = 'SAVE_INVOICE_FORM';
export const TRANSITION_TO_INVOICE = 'TRANSITION_TO_INVOICE';
export const TRANSITION_TO_DEAL = 'TRANSITION_TO_DEAL';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_REST = 'SUBMIT_FORM_REST';

